<?php

# this is autogenerated file, do not edit

return array (
  'c_upload' => 
  array (
    'j_delete' => 
    array (
      0 => 0,
      1 => 
      array (
      ),
      2 => 
      array (
      ),
      3 => 
      array (
        0 => 
        array (
          0 => '',
          1 => 'id',
          2 => '',
          3 => '\\d+',
          4 => 0,
        ),
      ),
    ),
  ),
);

